version: '3'
services:
  # db:
  #   image: mysql:5.7
  #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
  #   ports:
  #     - "33065:3306"
  #   volumes:
  #     - db-volume:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  # redis:
  #   image: redis:6.2.3
  #   ports:
  #     - "63790:6379"
  #   command: redis-server --appendonly yes
  #   volumes:
      #  - redis-volume:/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "bundle install;
                      rm /app/tmp/pids/server.pid;
                      bundle exec rails db:migrate;
                      bundle exec rails s -p 3001 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - bundle-volume:/usr/local/bundle
    environment:
      RAILS_ENV: development
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
      REDIS_HOST: redis
    # depends_on:
    #   - db
    #   - redis
volumes:
  # db-volume:
  #   driver: local
  bundle-volume:
    driver: local
